### ISSUE TITLE
Broken link in your help file

### ISSUE THREAD

**Issue by ericmelse** [drofphilosophe/Stata-fastgini#1]
Dear James,
Thank you for this Stata package. Reading the help file of `fgini`, note that the reference to _Accurate calculation of a Gini index using SAS and R_, by Vic Duoba and Nairn MacGibbon (also there is a writing error in your help file to be corrected, instead of on it should be MacGibbon ) is broken.
It currently can be found here: https://statsnz.contentdm.oclc.org/digital/collection/p20045coll1/id/4199/

Best regards,
Eric

**Comment by drofphilosophe** [comment]
@ericmelse - Thanks. I've merged a new version of the help file and put link in the repo landing page README.
